url
https://www.kaggle.com/datasets/uciml/faulty-steel-plates

데이터 정보
독립변수
- X_Minimum: 결함 주변 경계 상자의 최소 x 좌표입니다.
- X_Maximum: 결함 주변 경계 상자의 최대 x 좌표입니다.
- Y_Minimum: 결함 주변 경계 상자의 최소 y 좌표입니다.
- Y_Maximum: 결함 주변 경계 상자의 최대 y 좌표입니다.
- Pixels_Areas: 결함 내의 총 픽셀 수입니다.
- X_Perimeter: 결함의 x 축 주변 둘레입니다.
- Y_Perimeter: 결함의 y 축 주변 둘레입니다.
- Sum_of_Luminosity: 결함 영역의 총 빛의 합계입니다.
- Minimum_of_Luminosity: 결함 영역의 최소 빛 강도입니다.
- Maximum_of_Luminosity: 결함 영역의 최대 빛 강도입니다.
- Length_of_Conveyer: 컨베이어의 길이입니다.
- TypeOfSteel_A300: 강철 유형 중 A300인지 여부를 나타냅니다.
- TypeOfSteel_A400: 강철 유형 중 A400인지 여부를 나타냅니다.
- Steel_Plate_Thickness: 강판의 두께입니다.
- Edges_Index: 가장자리 지수입니다.
- Empty_Index: 빈 영역 지수입니다.
- Square_Index: 사각형 지수입니다.
- Outside_X_Index: X축 외부 지수입니다.
- Edges_X_Index: X축 가장자리 지수입니다.
- Edges_Y_Index: Y축 가장자리 지수입니다.
- Outside_Global_Index: 전체 외부 지수입니다.
- LogOfAreas: 결함 영역의 면적의 로그값입니다.
- Log_X_Index: X축 로그 지수입니다.
- Log_Y_Index: Y축 로그 지수입니다.
- Orientation_Index: 방향 지수입니다.
- Luminosity_Index: 빛의 강도 지수입니다.
- SigmoidOfAreas: 결함 영역의 로지스틱값입니다.

종속변수
- Pastry: 패스트리 결함의 여부를 나타냅니다.
- Z_Scratch: Z 스크래치 결함의 여부를 나타냅니다.
- K_Scatch: K 스크래치 결함의 여부를 나타냅니다.
- Stains: 얼룩 결함의 여부를 나타냅니다.
- Dirtiness: 더러움 결함의 여부를 나타냅니다.
- Bumps: 덩어리 결함의 여부를 나타냅니다.
- Other_Faults: 기타 결함의 여부를 나타냅니다.

In [1]:
# pip install numpy
# pip install pandas
# pip install -U scikit-learn
# pip install tensorflow


In [2]:
import csv
import numpy as np
import pandas as pd

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, log_loss

from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [3]:
route = "./data/"
file_name = "mulit_classification_data.csv"
df = pd.read_csv(route+file_name)

In [6]:
# file_name = "mulit_classification_data_engineering.csv"
# df_eda = pd.read_csv(route+file_name)

In [5]:
display(df.head(3), df.tail(3))

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   

   Maximum_of_Luminosity  ...  Orientation_Index  Luminosity_Index  \
0                    108  ...             0.8182           -0.2913   
1                    123  ...             0.7931           -0.1756   
2                    125  ...             0.6667           -0.1228   

   SigmoidOfAreas  Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  \
0          0.5822       1          0         0       0          0      0   
1          0.2984       1          0         0       0          0      0   
2          0.2150       1          0         0       0          0      0   

   Other_Faults  
0             0  
1             0  
2             0  

[3 rows x 34 columns]

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
1938        145        174     386779     386794           292           40   
1939        137        170     422497     422528           419           97   
1940       1261       1281      87951      87967           103           26   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
1938           22              37572                    120   
1939           47              52715                    117   
1940           22              11682                    101   

      Maximum_of_Luminosity  ...  Orientation_Index  Luminosity_Index  \
1938                    140  ...            -0.4828            0.0052   
1939                    140  ...            -0.0606           -0.0171   
1940                    133  ...            -0.2000           -0.1139   

      SigmoidOfAreas  Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  \
1938          0.7079       0          0         0       0          0      0   
1939          0.9919       0          0         0       0          0      0   
1940          0.5296       0          0         0       0          0      0   

      Other_Faults  
1938             1  
1939             1  
1940             1  

[3 rows x 34 columns]

In [6]:
# df.dtypes

In [7]:
# df.isna().sum()

In [8]:
# df.shape

In [9]:
# 데이터셋을 X와 y로 나누기
X = df.iloc[:,  0:27]    # 독립변수 (1열부터 27열까지)
y = df.iloc[:, 27:  ]    # 종속변수 (28열부터 34열까지)

In [10]:
# display(X.head(3), X.tail(3))
# display(y.head(3), y.tail(3))

In [ ]:
# 데이터를 훈련 세트와 테스트 세트로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

다중 분류

In [12]:
# y_train과 y_test를 1차원 배열로 변환
y_train = y_train.values.argmax(axis=1)
y_test = y_test.values.argmax(axis=1)

In [13]:
# Logistic Regression 모델 생성 및 학습
model = LogisticRegression(max_iter=7000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=7000, random_state=42)

In [14]:
# 테스트 세트로 예측 수행
y_pred = model.predict(X_test)

In [15]:
# 다중 분류 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print("다중 분류 정확도:", accuracy)

다중 분류 정확도: 0.5398457583547558


In [16]:
# 다중 분류 보고서 출력
print("다중 분류 보고서:")
print(classification_report(y_test, y_pred))

다중 분류 보고서:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.32      0.29      0.30        41
           2       0.94      0.75      0.83        83
           3       0.57      0.92      0.71        13
           4       0.00      0.00      0.00         8
           5       0.56      0.25      0.35        72
           6       0.46      0.74      0.57       143

    accuracy                           0.54       389
   macro avg       0.41      0.42      0.39       389
weighted avg       0.52      0.54      0.51       389



c:\Users\khan\anaconda3\envs\sec6_pj1\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\khan\anaconda3\envs\sec6_pj1\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\khan\anaconda3\envs\sec6_pj1\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


pipline

In [17]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier

# 파이프라인 생성: 데이터 스케일링 -> 로지스틱 회귀
model_pipe = make_pipeline(StandardScaler(), 
                           SGDClassifier(loss='log_loss', 
                                         max_iter=7000, 
                                         learning_rate='constant', 
                                         eta0=0.001, 
                                         random_state=42, 
                                         ))

In [18]:
# 학습 및 예측
model_pipe.fit(X_train, y_train)
y_pipe_pred = model_pipe.predict(X_test)

In [19]:
# 다중 분류 정확도 평가
accuracy = model_pipe.score(X_train, y_train)

# 테스트 세트의 log loss 점수 계산
y_pipe_prob = model_pipe.predict_proba(X_train)
log_loss_score = log_loss(y_train, y_pipe_prob)

print("Train 다중 분류 정확도:", accuracy)
print("Train Dataset log loss 점수:", log_loss_score)

Train 다중 분류 정확도: 0.7010309278350515
Train Dataset log loss 점수: 0.894154897518892


In [20]:
# # 다른 loss 확인용
# from sklearn.metrics import mean_squared_error

# # 테스트 데이터에 대한 예측
# y_pipe_pred_sample = model_pipe.predict(X_train)

# # Huber loss를 계산
# loss = mean_squared_error(y_train, y_pipe_pred_sample, squared=False)

# print("다중 분류 Huber Loss:", loss)

In [21]:
# 다중 분류 정확도 평가
accuracy = accuracy_score(y_test, y_pipe_pred)
print("Test 다중 분류 정확도:", accuracy)

Test 다중 분류 정확도: 0.7223650385604113


In [22]:
# 다중 분류 보고서 출력
print("다중 분류 보고서:")
print(classification_report(y_test, y_pipe_pred))

다중 분류 보고서:
              precision    recall  f1-score   support

           0       0.56      0.52      0.54        29
           1       0.73      0.85      0.79        41
           2       0.94      0.95      0.95        83
           3       0.92      0.85      0.88        13
           4       1.00      0.12      0.22         8
           5       0.58      0.58      0.58        72
           6       0.68      0.69      0.68       143

    accuracy                           0.72       389
   macro avg       0.77      0.65      0.66       389
weighted avg       0.73      0.72      0.72       389



test

In [23]:
y

Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  Other_Faults
0          1          0         0       0          0      0             0
1          1          0         0       0          0      0             0
2          1          0         0       0          0      0             0
3          1          0         0       0          0      0             0
4          1          0         0       0          0      0             0
...      ...        ...       ...     ...        ...    ...           ...
1936       0          0         0       0          0      0             1
1937       0          0         0       0          0      0             1
1938       0          0         0       0          0      0             1
1939       0          0         0       0          0      0             1
1940       0          0         0       0          0      0             1

[1941 rows x 7 columns]

In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [25]:
# 데이터 전처리 - 표준화 (Standardization)
scaler = StandardScaler()
X_sample = scaler.fit_transform(X)

In [26]:
X_sample

array([[-1.01648138, -1.14163891, -0.77772863, ...,  1.46765551,
        -1.0757517 , -0.00948966],
       [ 0.14189427,  0.06640322,  0.50018799, ...,  1.4175296 ,
        -0.2978242 , -0.845759  ],
       [ 0.49536213,  0.43625306, -0.05454637, ...,  1.16510269,
         0.05718506, -1.09151256],
       ...,
       [-0.81861622, -0.89239228, -0.71241235, ..., -1.13050437,
         0.91781358,  0.3609087 ],
       [-0.83398438, -0.9004325 , -0.69227956, ..., -0.28735056,
         0.76787595,  1.19776737],
       [ 1.32524319,  1.3327369 , -0.88084954, ..., -0.5657391 ,
         0.11702564, -0.16448532]])

In [27]:
def build_mlp_model(input_shape, num_classes):
    model = Sequential()

    # 은닉층 추가
    model.add(Dense(100, activation='relu', input_shape=input_shape))
    model.add(Dense(100, activation='relu'))

    # 출력층 추가 - 다중 레이블 문제를 위해 활성화 함수를 'sigmoid'로 변경
    model.add(Dense(num_classes, activation='sigmoid'))

    # 모델 컴파일 - 손실 함수를 'binary_crossentropy'로 변경
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

In [28]:
def train_and_evaluate_mlp(X, y):
    # 데이터 전처리 - 표준화 (Standardization)
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    # 데이터 분할 - 학습 데이터와 테스트 데이터로 분할합니다.
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # MLP 모델 생성
    input_shape = (X_train.shape[1],)
    num_classes = y_train.shape[1]  # 다중 레이블 문제이므로 y_train.shape[1]은 7입니다.
    model = build_mlp_model(input_shape, num_classes)

    # 모델 학습
    model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

    # 예측
    y_pred_prob = model.predict(X_test)
    y_pred = (y_pred_prob > 0.5).astype(int)

    # 성능 평가 - classification_report를 사용하여 클래스별 정밀도, 재현율, F1-score를 출력
    print("분류 결과 보고서:")
    print(classification_report(y_test, y_pred))

In [29]:
target_columns = ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']

X_test_sample = df.drop(columns=target_columns)
y_test_sample = df[target_columns]

# MLP 모델 학습 및 평가
train_and_evaluate_mlp(X_test_sample, y_test_sample)

Epoch 1/50
44/44 [==============================] - 1s 6ms/step - loss: 0.4383 - accuracy: 0.4534 - val_loss: 0.2844 - val_accuracy: 0.5385
Epoch 2/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2511 - accuracy: 0.5888 - val_loss: 0.2288 - val_accuracy: 0.6346
Epoch 3/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2134 - accuracy: 0.6669 - val_loss: 0.1982 - val_accuracy: 0.7115
Epoch 4/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1930 - accuracy: 0.7264 - val_loss: 0.1848 - val_accuracy: 0.7244
Epoch 5/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1812 - accuracy: 0.7357 - val_loss: 0.1845 - val_accuracy: 0.7179
Epoch 6/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1711 - accuracy: 0.7579 - val_loss: 0.1687 - val_accuracy: 0.7372
Epoch 7/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1646 - accuracy: 0.7622 - val_loss: 0.1683 - val_accuracy: 0.7564
Epoch 8/50
44/44 [==

c:\Users\khan\anaconda3\envs\sec6_pj1\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
target_columns = ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']

X_test_sample = df_eda.drop(columns=target_columns)
y_test_sample = df_eda[target_columns]

# MLP 모델 학습 및 평가
train_and_evaluate_mlp(X_test_sample, y_test_sample)

Epoch 1/50
44/44 [==============================] - 1s 6ms/step - loss: 0.4154 - accuracy: 0.4721 - val_loss: 0.2829 - val_accuracy: 0.5000
Epoch 2/50
44/44 [==============================] - 0s 3ms/step - loss: 0.2527 - accuracy: 0.5996 - val_loss: 0.2311 - val_accuracy: 0.6795
Epoch 3/50
44/44 [==============================] - 0s 3ms/step - loss: 0.2149 - accuracy: 0.6941 - val_loss: 0.1994 - val_accuracy: 0.7115
Epoch 4/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1948 - accuracy: 0.7342 - val_loss: 0.1837 - val_accuracy: 0.7564
Epoch 5/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1829 - accuracy: 0.7357 - val_loss: 0.1755 - val_accuracy: 0.7308
Epoch 6/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1744 - accuracy: 0.7536 - val_loss: 0.1739 - val_accuracy: 0.7436
Epoch 7/50
44/44 [==============================] - 0s 2ms/step - loss: 0.1656 - accuracy: 0.7679 - val_loss: 0.1690 - val_accuracy: 0.7372
Epoch 8/50
44/44 [==

c:\Users\khan\anaconda3\envs\sec6_pj1\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
y

Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  Other_Faults
0          1          0         0       0          0      0             0
1          1          0         0       0          0      0             0
2          1          0         0       0          0      0             0
3          1          0         0       0          0      0             0
4          1          0         0       0          0      0             0
...      ...        ...       ...     ...        ...    ...           ...
1936       0          0         0       0          0      0             1
1937       0          0         0       0          0      0             1
1938       0          0         0       0          0      0             1
1939       0          0         0       0          0      0             1
1940       0          0         0       0          0      0             1

[1941 rows x 7 columns]

In [32]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, MultiLabelBinarizer, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import multilabel_confusion_matrix


In [33]:
def preprocess_data(X, y):
    # StandardScaler를 사용하여 특성 스케일링
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # # 레이블을 숫자로 인코딩 후 0부터 시작하는 인덱스로 변환
    # label_encoder = LabelEncoder()
    # y_encoded = label_encoder.fit_transform(y)
    label_encoding = {
        'Other_Faults': 0,
        'Bumps': 1,
        'K_Scatch': 2,
        'Z_Scratch': 3,
        'Pastry': 4,
        'Stains': 5,
        'Dirtiness': 6
    }

    # 새로운 어레이에 라벨 인코딩 값을 저장
    y_encoded = y.apply(lambda row: label_encoding[y.columns[row.to_numpy().nonzero()[0][0]]], axis=1).values

    # 훈련 데이터와 테스트 데이터로 분리
    X_train, X_test, y_train_encoded, y_test_encoded = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

    return X_train, X_test, y_train_encoded, y_test_encoded


def train_and_evaluate_svm(X_train, X_test, y_train_bin, y_test_bin):
    # SVM 모델 생성
    model = SVC(kernel='linear', C=1.0)

    # 모델 학습
    model.fit(X_train, y_train_bin)

    # 예측
    y_pred_bin = model.predict(X_test)

    # 다중 레이블 문제에서의 정확도 평가
    accuracy = accuracy_score(y_test_bin, y_pred_bin)
    print("정확도:", accuracy)

    # 다중 레이블 문제에서의 오차 행렬
    ml_cm = multilabel_confusion_matrix(y_test_bin, y_pred_bin)
    for label, cm in zip(model.classes_, ml_cm):
        print(f"Label: {label}")
        print(cm)

    return model


In [34]:
# 데이터셋을 X와 y로 나누기
X = df.drop(columns=target_columns)
y = df[target_columns]

# 데이터 전처리
X_train, X_test, y_train_bin, y_test_bin = preprocess_data(X, y)

# SVM 모델 학습 및 평가
svm_model = train_and_evaluate_svm(X_train, X_test, y_train_bin, y_test_bin)

정확도: 0.7506426735218509
Label: 0
[[202  44]
 [ 41 102]]
Label: 1
[[288  29]
 [ 27  45]]
Label: 2
[[303   3]
 [  5  78]]
Label: 3
[[342   6]
 [  6  35]]
Label: 4
[[347  13]
 [ 12  17]]
Label: 5
[[376   0]
 [  1  12]]
Label: 6
[[379   2]
 [  5   3]]


In [35]:
# 데이터셋을 X와 y로 나누기
X_eda = df_eda.drop(columns=target_columns)
y_eda = df_eda[target_columns]

# 데이터 전처리
X_train, X_test, y_train_bin, y_test_bin = preprocess_data(X_eda, y_eda)

# SVM 모델 학습 및 평가
svm_model = train_and_evaluate_svm(X_train, X_test, y_train_bin, y_test_bin)

정확도: 0.7583547557840618
Label: 0
[[203  43]
 [ 38 105]]
Label: 1
[[288  29]
 [ 27  45]]
Label: 2
[[303   3]
 [  4  79]]
Label: 3
[[342   6]
 [  6  35]]
Label: 4
[[349  11]
 [ 12  17]]
Label: 5
[[376   0]
 [  1  12]]
Label: 6
[[379   2]
 [  6   2]]


### 순환 신경망(RNN)

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

def load_data(data):
    target_columns = ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']

    X = data.drop(columns=target_columns)
    y = data[target_columns]
    # 데이터 정규화
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 훈련 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    return X_train, X_test, y_train, y_test, scaler


def build_model(input_shape):
    model = Sequential()
    model.add(LSTM(128, input_shape=input_shape, return_sequences=True))
    model.add(Dropout(0.2))
    model.add(LSTM(64, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(7, activation='softmax'))
    return model

def compile_model(model):
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [37]:
def main():
    # 데이터 전처리
    X_train, X_test, y_train, y_test, scaler = load_data(df)

    # time steps 설정
    time_steps = 1  # 예시로 1로 설정했지만, 시퀀스 데이터의 길이에 맞게 조정 가능

    # shape 재구성 (samples, time steps, features)
    X_train = X_train.reshape(X_train.shape[0], time_steps, X_train.shape[1])
    X_test = X_test.reshape(X_test.shape[0], time_steps, X_test.shape[1])

    print("X_train shape:", X_train.shape)
    print("X_test shape:", X_test.shape)
    print("y_train shape:", y_train.shape)
    print("y_test shape:", y_test.shape)

    # 모델 구축
    input_shape = (X_train.shape[1], X_train.shape[2])
    model = build_model(input_shape)

    # 모델 컴파일
    model = compile_model(model)

    # 모델 훈련
    history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

    # 모델 평가
    loss, accuracy = model.evaluate(X_test, y_test)
    print(f'Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}')

if __name__ == "__main__":
    main()

X_train shape: (1552, 1, 27)
X_test shape: (389, 1, 27)
y_train shape: (1552, 7)
y_test shape: (389, 7)
Epoch 1/50
39/39 [==============================] - 4s 30ms/step - loss: 1.7508 - accuracy: 0.4327 - val_loss: 1.4914 - val_accuracy: 0.4984
Epoch 2/50
39/39 [==============================] - 0s 7ms/step - loss: 1.4089 - accuracy: 0.4851 - val_loss: 1.2262 - val_accuracy: 0.5305
Epoch 3/50
39/39 [==============================] - 0s 6ms/step - loss: 1.1892 - accuracy: 0.5576 - val_loss: 1.0151 - val_accuracy: 0.6367
Epoch 4/50
39/39 [==============================] - 0s 6ms/step - loss: 0.9877 - accuracy: 0.6495 - val_loss: 0.8682 - val_accuracy: 0.6849
Epoch 5/50
39/39 [==============================] - 0s 6ms/step - loss: 0.8651 - accuracy: 0.6704 - val_loss: 0.7871 - val_accuracy: 0.7170
Epoch 6/50
39/39 [==============================] - 0s 7ms/step - loss: 0.8072 - accuracy: 0.7019 - val_loss: 0.7491 - val_accuracy: 0.7395
Epoch 7/50
39/39 [==============================] - 0s 

In [38]:
def main():
    # 데이터 전처리
    X_train, X_test, y_train, y_test, scaler = load_data(df_eda)

    # time steps 설정
    time_steps = 1  # 예시로 1로 설정했지만, 시퀀스 데이터의 길이에 맞게 조정 가능

    # shape 재구성 (samples, time steps, features)
    X_train = X_train.reshape(X_train.shape[0], time_steps, X_train.shape[1])
    X_test = X_test.reshape(X_test.shape[0], time_steps, X_test.shape[1])

    print("X_train shape:", X_train.shape)
    print("X_test shape:", X_test.shape)
    print("y_train shape:", y_train.shape)
    print("y_test shape:", y_test.shape)

    # 모델 구축
    input_shape = (X_train.shape[1], X_train.shape[2])
    model = build_model(input_shape)

    # 모델 컴파일
    model = compile_model(model)

    # 모델 훈련
    history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

    # 모델 평가
    loss, accuracy = model.evaluate(X_test, y_test)
    print(f'Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}')

if __name__ == "__main__":
    main()

X_train shape: (1552, 1, 24)
X_test shape: (389, 1, 24)
y_train shape: (1552, 7)
y_test shape: (389, 7)
Epoch 1/50
39/39 [==============================] - 4s 26ms/step - loss: 1.7962 - accuracy: 0.4553 - val_loss: 1.5256 - val_accuracy: 0.5563
Epoch 2/50
39/39 [==============================] - 0s 7ms/step - loss: 1.4251 - accuracy: 0.5052 - val_loss: 1.2293 - val_accuracy: 0.5691
Epoch 3/50
39/39 [==============================] - 0s 7ms/step - loss: 1.1895 - accuracy: 0.5552 - val_loss: 1.0434 - val_accuracy: 0.6109
Epoch 4/50
39/39 [==============================] - 0s 6ms/step - loss: 1.0231 - accuracy: 0.6180 - val_loss: 0.9216 - val_accuracy: 0.6559
Epoch 5/50
39/39 [==============================] - 0s 6ms/step - loss: 0.9110 - accuracy: 0.6608 - val_loss: 0.8417 - val_accuracy: 0.7106
Epoch 6/50
39/39 [==============================] - 0s 6ms/step - loss: 0.8347 - accuracy: 0.6978 - val_loss: 0.7886 - val_accuracy: 0.7170
Epoch 7/50
39/39 [==============================] - 0s 

In [39]:
def main():
    # 데이터 전처리
    X_train, X_test, y_train, y_test, scaler = load_data(df)

    # time steps 설정
    time_steps = 1  # 예시로 1로 설정했지만, 시퀀스 데이터의 길이에 맞게 조정 가능

    # shape 재구성 (samples, time steps, features)
    X_train = X_train.reshape(X_train.shape[0], time_steps, X_train.shape[1])
    X_test = X_test.reshape(X_test.shape[0], time_steps, X_test.shape[1])

    # 모델 구축
    input_shape = (X_train.shape[1], X_train.shape[2])
    model = build_model(input_shape)

    # 모델 컴파일
    model = compile_model(model)

    # 원래 모델 성능 평가
    original_loss, original_accuracy = model.evaluate(X_test, y_test)
    print(f'Original Test loss: {original_loss:.4f}, Original Test accuracy: {original_accuracy:.4f}')

    # 컬럼을 하나씩 드랍하면서 모델 성능 테스트
    for i in range(X_train.shape[2]):
        # 원본 데이터에서 해당 컬럼을 제거하여 새로운 데이터 생성
        X_train_temp = np.delete(X_train, i, axis=2)
        X_test_temp = np.delete(X_test, i, axis=2)

        # 모델 구축
        input_shape_temp = (X_train_temp.shape[1], X_train_temp.shape[2])
        model_temp = build_model(input_shape_temp)

        # 모델 컴파일
        model_temp = compile_model(model_temp)

        # 모델 훈련
        history_temp = model_temp.fit(X_train_temp, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=0)

        # 모델 평가
        loss_temp, accuracy_temp = model_temp.evaluate(X_test_temp, y_test)
        print(f'After dropping column {i+1}: Test loss: {loss_temp:.4f}, Test accuracy: {accuracy_temp:.4f}')

if __name__ == "__main__":
    main()

13/13 [==============================] - 1s 3ms/step - loss: 1.9492 - accuracy: 0.1105
Original Test loss: 1.9492, Original Test accuracy: 0.1105
13/13 [==============================] - 0s 2ms/step - loss: 0.6531 - accuracy: 0.7686
After dropping column 1: Test loss: 0.6531, Test accuracy: 0.7686
13/13 [==============================] - 0s 3ms/step - loss: 0.6534 - accuracy: 0.7558
After dropping column 2: Test loss: 0.6534, Test accuracy: 0.7558
13/13 [==============================] - 0s 3ms/step - loss: 0.6490 - accuracy: 0.7686
After dropping column 3: Test loss: 0.6490, Test accuracy: 0.7686
13/13 [==============================] - 0s 2ms/step - loss: 0.6638 - accuracy: 0.7532
After dropping column 4: Test loss: 0.6638, Test accuracy: 0.7532
13/13 [==============================] - 0s 3ms/step - loss: 0.6714 - accuracy: 0.7532
After dropping column 5: Test loss: 0.6714, Test accuracy: 0.7532
13/13 [==============================] - 0s 2ms/step - loss: 0.6398 - accuracy: 0.7841
Af